let products = [
  {
    id: 1,
    name: "pantalon",
    price: 1000,
    size: ["s", "m"],
    gender: "mujer",
    category: "pantalones",
  },
  {
    id: 2,
    name: "pantalon largo",
    price: 1000,
    size: ["s", "m", "l", "xxl"],
    gender: "hombre",
    category: "pantalones",
  },
  {
    id: 3,
    name: "pantalon corto",
    price: 3000,
    size: ["m", "l", "xl"],
    gender: "hombre",
    category: "pantalones",
  },
  {
    id: 4,
    name: "remera manga corta",
    price: 2000,
    size: ["s", "m", "l"],
    gender: "mujer",
    category: "remeras",
  },
  {
    id: 5,
    name: "remera manga larga",
    price: 2500,
    size: ["s", "l", "xl"],
    gender: "mujer",
    category: "remeras",
  },
  {
    id: 6,
    name: "saco",
    price: 3000,
    size: ["l", "xl"],
    gender: "hombre",
    category: "sacos",
  },
  {
    id: 7,
    name: "saco de pana",
    price: 3000,
    size: ["l", "xl"],
    gender: "hombre",
    category: "sacos",
  },
  {
    id: 8,
    name: "vestido largo",
    price: 4000,
    size: ["s","m", "l"],
    gender: "mujer",
    category: "vestidos",
  },
  {
    id: 9,
    name: "vestido corto",
    price: 4000,
    size: ["m", "l"],
    gender: "mujer",
    category: "vestidos",
  },
  {
    id: 10,
    name: "campera",
    price: 5000,
    size: ["xl", "xxl"],
    gender: "hombre",
    category: "camperas",
  },
  {
    id: 11,
    name: "campera lluvia",
    price: 3000,
    size: ["xl", "xxl"],
    gender: "hombre",
    category: "camperas",
  },
  {
    id: 12,
    name: "pantalon corto negro",
    price: 3000,
    size: ["m", "l", "xl"],
    gender: "hombre",
    category: "pantalones",
  },
];

